# Generated by Django 4.0.5 on 2022-06-07 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('NameDeEntreprise', models.CharField(default='NomEntreprise', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdSite', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Marque', models.CharField(max_length=100)),
                ('IP_ADD', models.CharField(max_length=50)),
                ('TYPE', models.CharField(choices=[('R', 'Reseau'), ('S', 'Switch'), ('F', 'Fédérateur'), ('MP', 'Machinepysique')], max_length=5)),
                ('Local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.local')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='Site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.site'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeDeContrat', models.CharField(choices=[('CM', 'Contratmaintenence'), ('CA', 'Contratacquisition')], default='TypeDeContrat', max_length=10)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('Equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.equipement')),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.fournisseur')),
            ],
        ),
    ]
