# Generated by Django 4.0.5 on 2022-06-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='Mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='NumeroTéléphone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
