# Generated by Django 4.0.5 on 2022-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0003_departement_iddepartement_local_idlocal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='IP_ADD',
            field=models.GenericIPAddressField(),
        ),
    ]
